---
- name: Deploy the TGWF dataset browser
  hosts:
    - all
  remote_user: "deploy"
  become: false

  vars:
    project_git_repo: "git@github.com:thegreenwebfoundation/dataset-browser.git"
    project_deploy_strategy: git
    project_version: "main"
    project_local_path: "../"
    project_unwanted_items:
      - .git
    project_finalize: true
    service_user: "deploy"
    supervisor_user: "deploy"
    install_system_dependencies: false
    install_python_dependencies: true
    # set this to true this to make sure the run script fetches 
    # the latest snapshot of the dataset from object storage
    fetch_new_snapshot: true
    check_site_available: false

  roles:
    - f500.project_deploy

  tasks:
    - name: Set up directory structure for project_deploys, and env files
      block:
        - name: Set up directory for deploying app
          ansible.builtin.file:
            path: "/var/www/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
            state: directory
            mode: "0755"
            owner: deploy
            group: deploy
          become: true

        - name: Move .env file to shared directory
          ansible.builtin.template:
            src: "templates/dotenv.j2"
            dest: "{{ project_root }}/shared/.env"
            owner: deploy
            group: deploy
            mode: "0755"
          become: true

        - name: Link .env to shared directory
          ansible.builtin.file:
            src: "{{ project_root }}/shared/.env"
            dest: "{{ project_root }}/current/.env"
            state: link

    - name: Install required system dependencies
      when: install_system_dependencies is true
      block:
        - name: Make sure python is installed
          ansible.builtin.apt:
            pkg:
              - python3-venv
              - python3-dev
              - jq
            state: present
          become: true

    - name: Install required application dependencies
      ansible.builtin.command: "/home/deploy/.cargo/bin/uv sync" # noqa no-changed-when
      args:
        chdir: "{{ project_root }}/current"
      when: install_python_dependencies is true

    - name: Set up systemd service for datasette
      ansible.builtin.template:
        src: "systemd.dataset_browser.service.j2"
        dest: "/etc/systemd/system/dataset_browser.service"
        owner: deploy
        group: deploy
        mode: "0755"
      become: true
      tags:
        - systemd
        - config

    - name: Set up script for running app via systemd
      ansible.builtin.template:
        src: "run_dataset_browser.sh.j2"
        dest: "{{ project_root }}/current/run_dataset_browser.sh"
        owner: deploy
        group: deploy
        mode: "0755"
      become: true
      tags:
        - systemd
        - run_script

    - name: Reload systemd to pick up new changes
      ansible.builtin.systemd:
        daemon_reload: true
      become: true
      tags:
        - systemd
        - config

    - name: Check that website is serving requests on expected domains
      when: check_site_available is true
      ansible.builtin.uri:
        url: "https://{{ tgwf_domain_name }}.{{ item }}"
        return_content: true
        status_code: 200
        timeout: 5
      loop:
        - greenweb.org
        - thegreenwebfoundation.org
      tags:
        - smoke-test
        - config
