---
- name: Deploy the TGWF dataset browser
  hosts:
    - all
  remote_user: "deploy"
  become: no

  vars:
    project_git_repo: "git@github.com:thegreenwebfoundation/dataset-browser.git"
    project_deploy_strategy: git
    project_version: "main"
    project_local_path: "../"
    restart_supervisor: true
    supervisor_user: "deploy"
    project_unwanted_items:
      - .git

    project_finalize: true

  roles:
    - f500.project_deploy

  tasks:
    - name: set up directory for deploying app
      file:
        path: "/var/www/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
        state: directory
        mode: "0755"
        owner: deploy
        group: deploy
      become: yes

    - name: move .env file to shared directory
      template:
        src: "templates/dotenv.j2"
        dest: "{{ project_root }}/shared/.env"
      become: yes

    - name: Link .env to shared directory
      file:
        src: "{{ project_root }}/shared/.env"
        dest: "{{ project_root }}/current/.env"
        state: link

    - name: make sure python is installed
      apt:
        pkg:
          - python3-venv
          - python3-dev
        state: present
      become: yes

    - name: install python dependencies with pipenv
      shell: "pipenv sync --three"
      args:
        chdir: "{{ project_root }}/current"

    - name: set up nginx server entry
      template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
      become: yes

    - name: Create a symbolic to make nginx file appear in sites-enabled
      file:
        src: "/etc/nginx/sites-available/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
        dest: "/etc/nginx/sites-enabled/{{ tgwf_domain_name }}.thegreenwebfoundation.org"
        state: link
      become: yes

    - name: set up script for running app, via supervisor
      template:
        src: "run_dataset_browser.sh.j2"
        dest: "{{ project_root }}/current/run_dataset_browser.sh"
      become: yes

    - name: set up supervisor entry for web
      template:
        src: "supervisor.dataset_browser.conf.j2"
        dest: "/etc/supervisor/conf.d/{{ tgwf_domain_name }}_web.conf"
      become: yes

    - name: trigger restart for app with supervisor
      supervisorctl:
        name: dataset_browser
        state: restarted
      become: yes

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
      become: yes
