name: Deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use turnstyle to serialise deploys
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
          options: |
            --inventory inventories/prod
        env:
          BUCKET_NAME: tgwf-green-domains-live
          ANSIBLE_STDOUT_CALLBACK: debug
