name: Deploy

on: [push]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
          options: |
            --inventory inventories/prod
        env:
          BUCKET_NAME: tgwf-green-domains-live
          ANSIBLE_STDOUT_CALLBACK: debug
