name: Deploy

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5


    - name: Play Ansible Playbook
      uses: arillso/action.playbook@master
      with:
        private_key: ${{secrets.SSH_PRIVATE_KEY}}
        playbook: ansible/playbook.yml
        inventory: ansible/prod
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_DEPRECATION_WARNINGS: 'false'

    - name: tmate session to debug failure
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
