name: Deploy

on: [push]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add private key to SSH agent, so ansible can use it
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Play Ansible Playbook
        run: >
          ansible-playbook
          ansible/testing.yml
          -i ansible/inventories/prod
        env:
          BUCKET_NAME: "tgwf-green-domains-live"
