name: Deploy

on: [push]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: testing.yml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
          options: |
            --verbose
            --inventory inventories/prod
