name: Deploy

on: [push]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: pip install ansible paramiko
        run: python -m pip install paramiko ansible

      - name: Add key to connect with ansible
        run: bash ansible/create_keyfile_for_actions.sh
        env:
          KEY_MATERIAL: ${{ secrets.SSH_PRIVATE_KEY }}
        working-directory: ./

      - name: Play Ansible Playbook
        run: |
          ansible-playbook
          ansible/testing.yml
          -i ansible/inventories/prod
          --key=file deploy_keyfile
        env:
          BUCKET_NAME: "tgwf-green-domains-live"
        working-directory: ./
