name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: Make sure we have ansible installed
        run: sudo apt install ansible --yes

      - name: Add key to connect with ansible
        run: |
          cat $KEY_MATERIAL > deploy_keyfile
          chmod 0600 deploy_keyfile
        env:
          KEY_MATERIAL: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Play Ansible Playbook
        run: |
          ansible-playbook
          ansible/testing.yml
          -i ansible/inventories/prod
          --key=file deploy_keyfile
        env:
          BUCKET_NAME: "tgwf-green-domains-live"
