name: Run Tests

on: [push]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/setup-just
      - uses: extractions/setup-just@v2
        name: install just

        # https://docs.astral.sh/uv/guides/integration/github/
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.0"
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: just test
